services:
    backend:
        build: ./backend
        restart: always
        volumes:
            - frontend-dist:/app/frontend-build
        ports:
            - "8080:8080"
        environment:
            - GIN_MODE=release
        depends_on:
            - db
            - frontend

    db:
        image: mongo
        restart: always
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"

    frontend:
        build: ./frontend
        volumes:
            - frontend-dist:/app/dist
        environment:
            - NODE_ENV=production

volumes:
    frontend-dist: